kind: pipeline
type: docker
name: USMAN.NET CI/CD

steps:
- name: Black Code Format Check
  image: juliopdx/netauto
  commands:
  - black . --check
- name: Install and deploy
  image: python
  commands:
  - pip3 install -r requirements.txt
  - python3 main.py

trigger:
  branch:
    exclude:
    - pull_request
