kind: pipeline
type: docker
name: Testing Python CI/CD

steps:
- name: Install and deploy
  image: python
  commands:
  - pip3 install -r requirements.txt
  - python3 main.py

trigger:
  branch:
    exclude:
    - pull_request
