kind: pipeline
type: docker
name: USMAN.NET CI/CD

steps:
- name: Install and deploy
  image: python
  commands:
  - pip3 install -r requirements.txt
  - python3 main.py

  when:
    branch:
    - master
    - main
    exclude:
    - pull_request

trigger:
  exclude:
    - pull_request