kind: pipeline
type: docker
name: USMAN.NET CI/CD

steps:
- name: Run Linter Tests
  image: python
  commands:
  - python3 hello.py

- name: Install Requirements and Deploy
  image: python
  commands:
  - pip3 install -r requirements.txt
  - python3 main.py
  when:
    branch:
    - main

trigger:
  exclude:
    - pull_request