routers:
  - name: "edge-dn42-lan"
    SSH_conf:
      hostname: "edge.dn42.lan"
      username: "test"
      password: "test"
      use_keys: False
      key_location: ""
      secret: ""
    
    firewalls:

      - name: "Tunnels_In_v4"
        state: "present"
        default_action: "drop"
        rules:
          - rule_no: "60"
            state: "present"
            action: "accept"
            desc: "Allow ICMP to zahid-erx test"
            dest: "address 172.23.132.173"
            protocol: "icmp"

          - rule_no: "65"
            state: "present"
            action: "drop"
            desc: "Block Traffic to Operator Assigned IP Space"
            dest: "address 172.22.132.160/27"

          - rule_no: "70"
            state: "present"
            action: "accept"
            desc: "Allow Peer Transit"
            dest: "group network-group Allowed-Transit-v4"
            source: "group network-group 'Allowed-Transit-v4'"

          - rule_no: "99"
            state: "present"
            action: "drop"
            desc: "Black Hole"

      - name: "WAN_Local"
        state: "present"
        default_action: "drop"
        rules:
          - rule_no: "10"
            state: "present"
            action: "accept"
            desc: "accept SSH"
            dest: "port 22"
            source: ""
            protocol: "tcp_udp"

          - rule_no: "20"
            state: "present"
            action: "accept"
            desc: "accept ICMP pings"
            protocol: "icmp"

          - rule_no: "30"
            state: "present"
            action: "accept"
            desc: "accept wg 51890"
            dest: "port 51890"
            source: ""
            protocol: "udp"

          - rule_no: "40"
            state: "present"
            action: "accept"
            desc: "accept wg 51899"
            dest: "port 51899"
            protocol: "udp"

          - rule_no: "50"
            state: "present"
            action: "accept"
            desc: "accept chrismoos wg in"
            dest: "port 51877"
            protocol: "udp"

          - rule_no: "60"
            state: "present"
            action: "accept"
            desc: "accept in from zahid p2p"
            dest: "port 51893"
            protocol: "udp"

          - rule_no: "70"
            state: "present"
            action: "accept"
            desc: "accept from wg joel "
            dest: "port 51720"
            protocol: "udp"


          - rule_no: "80"
            state: "present"
            action: "accept"
            desc: "accept wg from CA iBGP"
            dest: "port 51730"
            protocol: "udp"

          - rule_no: "90"
            state: "present"
            action: "accept"
            desc: "allow estab related traffic"
            states:
              - name: "established"
                status: "present"
              - name: "related"
                status: "enabled"

    interfaces:
      - name: "eth0"
        type: "ethernet"
        state: "present"
        ip: "dhcp"
        mask: ""
        desc: "WAN"

      - name: "lo"
        type: "loopback"
        state: "present"
        ip: "10.100.100.4"
        mask: "/32"
        desc: "edge-dn42-lan"

      - name: "wg11"
        type: "wireguard"
        state: "present"
        ip: "172.22.132.177"
        mask: "/31"
        desc: "p2p_zahid"
        port: "51893"
        wg_peers:
          - name: "zahid"
            allowedips: "0.0.0.0/0"
            endpoint: "91.135.14.109:51891"
            pubkey: "GFeyDtmAqToUd2xiQ6nPXKG2/WVvZrhaD5rlSwNpw2Y="

      - name: "wg12"
        type: "wireguard"
        state: "present"
        ip: "172.22.132.170"
        mask: "/30"
        desc: "p2p_usman"
        port: "51890"
        wg_peers:
          - name: "erx"
            allowedips: "0.0.0.0/0"
            endpoint: "home.usman.network:51891"
            pubkey: "UbhSaUPiASdfKB6G/Jz6JHeSM2zp+MJ2THWyUVoyBUY="
    
      - name: "wg13"
        type: "wireguard"
        state: "present"
        ip: "172.22.132.166"
        mask: "/32"
        desc: "DN42_Kioubit"
        firewall:
          - name: "Tunnels_In_v4"
            direction: "in"
          - name: "Tunnels_Local_v4"
            direction: "local"
        wg_peers:
          - name: "kioubit"
            allowedips: "0.0.0.0/0"
            endpoint: "uk1.g-load.eu:21869"
            keepalive: "60"
            pubkey: "sLbzTRr2gfLFb24NPzDOpy8j09Y6zI+a7NkeVMdVSR8="


      - name: "wg14"
        type: "wireguard"
        state: "present"
        ip: "172.22.132.166"
        mask: "/32"
        desc: "DN42_highdef"
        firewall:
          - name: "Tunnels_In_v4"
            direction: "in"
          - name: "Tunnels_Local_v4"
            direction: "local"
        wg_peers:
          - name: "highdef"
            allowedips: "0.0.0.0/0"
            endpoint: "185.164.136.218:21869"
            keepalive: "60"
            pubkey: "pEQZQOD67QeWXqrHLrMoCXug/cOXJFMXH5vwQ1cW70s="

      - name: "wg15"
        type: "wireguard"
        state: "present"
        ip: "172.22.132.166"
        mask: "/32"
        desc: "DN42_chrismoos"
        port: "51877"
        firewall:
          - name: "Tunnels_In_v4"
            direction: "in"
          - name: "Tunnels_Local_v4"
            direction: "local"
        wg_peers:
          - name: "chr"
            allowedips: "0.0.0.0/0"
            endpoint: "95.179.251.165:58642"
            pubkey: "MD1EdVe9a0yycUdXCH3A61s3HhlDn17m5d07e4H33S0="

      - name: "wg16"
        type: "wireguard"
        state: "present"
        ip: "172.22.132.166"
        mask: "/32"
        desc: "DN42_Pebcak"
        firewall:
          - name: "Tunnels_In_v4"
            direction: "in"
          - name: "Tunnels_Local_v4"
            direction: "local"
        wg_peers:
          - name: "DN42_Pebcak"
            allowedips: "0.0.0.0/0"
            endpoint: "95.179.144.2:51869"
            keepalive: "60"
            pubkey: "g4MJv6qMPwbffxNjUKmIa5Yhf5ZzRqjIMzMHCSiFQgs="

      - name: "wg17"
        type: "wireguard"
        state: "present"
        ip: "172.22.132.166"
        mask: "/32"
        desc: "joel"
        port: "51720"
        firewall:
          - name: "Tunnels_In_v4"
            direction: "in"
          - name: "Tunnels_Local_v4"
            direction: "local"
        wg_peers:
          - name: "joel"
            allowedips: "0.0.0.0/0"
            endpoint: "chi-r02.pub.joelheaps.com:50013"
            pubkey: "lVJwCvlEO3J9dWSe0bRaReYOaTtq1heUtQgQK7NnEn8="

      - name: "wg18"
        type: "wireguard"
        state: "deleted"
        ip: "172.22.132.179"
        mask: "/31"
        desc: "p2p_iBGP_CA"
        port: "51730"
        wg_peers:
          - name: "CA"
            allowedips: "0.0.0.0/0"
            endpoint: "194.147.71.143:51731"
            pubkey: "tT41B5fOSLrp9Q1ja3MaXxqa0MLfrvtalyvK2zZ5xTQ="

    bgpasn: "4242421869"

    bgp_prefixes:
      - prefix: "172.22.132.160"
        mask: "/27"
        address_family: "ipv4-unicast"
        state: "present"

      - prefix: "10.100.100.4"
        mask: "/32"
        address_family: "ipv4-unicast"
        state: "present"
    
    bgp_peers:

      - ip: "172.20.53.104"
        state: "present"
        remote_as: "4242423914"
        ebgp_multihop: "255"
        desc: "kioubit"
        route_maps:
          - route_map: "DN42-ROA"
            action: "import"
            state: "present"
          - route_map: "DN42-ROA"
            action: "export"
            state: "present"
      
      - ip: "172.20.16.141"
        state: "present"
        remote_as: "4242421588"
        ebgp_multihop: "250"
        desc: "chrismoos"
        route_maps:
          - route_map: "DN42-ROA"
            action: "import"
            state: "present"
          - route_map: "DN42-ROA"
            action: "export"
            state: "present"

      - ip: "172.21.67.200"
        state: "present"
        remote_as: "4242422092"
        ebgp_multihop: "255"
        desc: "pebcak"
        route_maps:
          - route_map: "DN42-ROA"
            action: "import"
            state: "present"
          - route_map: "DN42-ROA"
            action: "export"
            state: "present"

      - ip: "172.20.229.116"
        state: "present"
        remote_as: "4242421080"
        ebgp_multihop: "250"
        desc: "highdef"
        route_maps:
          - route_map: "DN42-ROA"
            action: "import"
            state: "present"
          - route_map: "DN42-ROA"
            action: "export"
            state: "present"

      - ip: "172.23.120.49"
        state: "present"
        remote_as: "4242421720"
        ebgp_multihop: "250"
        desc: "joel"
        route_maps:
          - route_map: "DN42-ROA"
            action: "import"
            state: "present"
          - route_map: "DN42-ROA"
            action: "export"
            state: "present"



    static:
      - type: "interface-route"
        network: "172.20.16.141/32"
        nexthop: "wg15"
        distance: ""
        state: "present"

      - type: "interface-route"
        network: "172.20.53.104/32"
        nexthop: "wg13"
        distance: ""
        state: "present"

      - type: "interface-route"
        network: "172.20.229.116/32"
        nexthop: "wg14"
        distance: ""
        state: "present"

      - type: "interface-route"
        network: "172.21.67.200/32"
        nexthop: "wg16"
        distance: ""
        state: "present"
        desc: "pebcak"

      - type: "interface-route"
        network: "172.23.120.49/32"
        nexthop: "wg17"
        distance: ""
        state: "present"
        desc: "joel"

    route_maps:
      - name: "DN42-ROA"
        desc: "DN42RouteMap"
        rules:
        - rule_no: "30"
          state: "present"
          action: "permit"
          match: "ip address prefix-list filter-import"

        - rule_no: "40"
          state: "present"
          action: "deny"
          match: "ip address prefix-list block-other-ranges"

        - rule_no: "50"
          state: "present"
          action: "deny"
          match: "rpki invalid"

    prefix_lists:
      - name: "block-other-ranges"
        desc: "blocks-other-ranges"
        rules:
        - rule_no: "10"
          state: "present"
          action: "deny"
          match:
          - prefix: "10.0.0.0/8"
            length: "le 32"
            # length: "ge 10"

      - name: "filter-import"
        desc: "filter imports to only include DN42 range"
        rules:
        - rule_no: "1"
          state: "present"
          action: "permit"
          match:
          - prefix: "172.20.0.0/14"
            length: "le 32"

    ospf:
      ospf_redistribute:
        - redistribute: "bgp"
          # route_map: ""
          state: "present"

      ospf_parameters:
        use_routerid: False
        routerid: ""
      ospf_networks:
        - subnet: "10.100.100.0"
          mask: "/24"
          area: "0"
          state: "present"
        - subnet: "172.22.132.176"
          mask: "/31"
          area: "0"
          state: "present"
        - subnet: "172.22.132.168"
          mask: "/30"
          area: "0"
          state: "present"