
routers:
  - name: "us-ca1"
    SSH_conf:
      hostname: "194.147.71.158"
      username: "vyos"
      password: "test"
      use_keys: False
      key_location: ""
      secret: ""

    groups:
      state: "replaced"
      config:
        - name: "Allowed-Transit-v4"
          state: present
          type: network
          desc: "Allowed Transit Networks for DN42"
          networks:
            - "172.20.0.0/14"
            - "172.31.0.0/16"

        - name: "Allowed-Transit-v6"
          state: "present"
          type: "ipv6-network"
          desc: "Allowed v6 Transit Network for DN42"
          networks:
            - "fd00::/8"

        - name: "My-Assigned-Space-v6"
          state: "present"
          type: "ipv6-network"
          desc: "My Assigned v6 Space for DN42"
          networks:
            - "fd5f:2bd0:1feb::/48"

    firewalls:
      state: "replaced"
      config:

        - name: "Tunnels_In_v4"
          state: "present"
          default_action: "drop"
          rules:
            - rule_no: "50"
              state: "present"
              action: "accept"
              protocol: "icmp"
              desc: "Accept ICMP to all"

            - rule_no: "60"
              state: "present"
              action: "accept"
              protocol: "tcp_udp"
              desc: "Allow web traffic to blog server"
              dest: 
                - address: "172.22.132.186/32"
                - port: "80"

            - rule_no: "61"
              state: "present"
              action: "accept"
              protocol: "tcp_udp"
              desc: "Allow DNS traffic to blog/DNS server (rasp pi)"
              dest: 
                - address: "172.22.132.186/32"
                - port: "53"

            - rule_no: "65"
              state: "present"
              action: "accept"
              desc: "allow estab related traffic"
              states:
                - name: "established"
                  status: "present"
                - name: "related"
                  status: "enabled"

            - rule_no: "97"
              state: "present"
              action: "drop"
              desc: "Block Traffic to Operator Assigned IP Space"
              dest: 
                - address: "172.22.132.160/27"

            - rule_no: "98"
              state: "present"
              action: "accept"
              desc: "Allow Peer Transit"
              dest: 
                - group: "network-group Allowed-Transit-v4"
              source: 
                - group: "network-group Allowed-Transit-v4"

            - rule_no: "99"
              state: "present"
              action: "drop"
              desc: "Black Hole"

        - name: "Tunnels_Local_v4"
          state: "present"
          default_action: "drop"
          rules:
            - rule_no: "50"
              state: "present"
              action: "accept"
              protocol: "icmp"
              desc: "Accept ICMP to all"

            - rule_no: "60"
              state: "present"
              action: "accept"
              protocol: "tcp"
              desc: "Allow BGP Sessions"
              dest: 
                - port: "179"

            - rule_no: "140"
              state: "present"
              action: "accept"
              desc: "allow estab related traffic"
              states:
                - name: "established"
                  status: "present"
                - name: "related"
                  status: "enabled"

            - rule_no: "150"
              state: "present"
              action: "drop"
              protocol: ""
              desc: "Black Hole"


        - name: "WAN_Local"
          state: "present"
          default_action: "drop"
          rules:
            - rule_no: "10"
              state: "present"
              action: "accept"
              desc: "accept SSH"
              dest: 
                - port: "22"
              source: 
                - address: "82.14.78.220"
              protocol: "tcp_udp"

            - rule_no: "20"
              state: "present"
              action: "accept"
              desc: "accept ICMP pings"
              protocol: "icmp"

            - rule_no: "30"
              state: "present"
              action: "accept"
              desc: "accept wg 51802 (fr-lil1<>us-ca1)"
              dest: 
                - port: "51802"
              source: ""
              protocol: "udp"


    firewalls6:
      state: replaced
      config:
        - name: "Tunnels_In_v6"
          state: "present"
          default_action: "drop"
          rules:
            - rule_no: "68"
              state: "present"
              action: "drop"
              desc: "Block Traffic to Operator Assigned IP Space"
              dest: 
                - group: "network-group My-Assigned-Space-v6 "

            - rule_no: "70"
              state: "present"
              action: "accept"
              desc: "Allow Peer Transit"
              dest: 
                - group: "network-group Allowed-Transit-v6"
              source: 
                - group: "network-group Allowed-Transit-v6"

            - rule_no: "99"
              state: "present"
              action: "drop"
              desc: "Black Hole"

        - name: "Tunnels_Local_v6"
          state: "present"
          default_action: "drop"
          rules:
            - rule_no: "50"
              state: "present"
              action: "accept"
              desc: "Block Traffic to Operator Assigned IP Space"
              protocol: "ipv6-icmp"

            - rule_no: "61"
              state: "present"
              action: "accept"
              desc: "Allow BGP"
              protocol: "tcp"
              dest: 
                - port: "179"

            - rule_no: "99"
              state: "present"
              action: "drop"
              desc: "Black Hole"

    interfaces:
      - name: "eth0"
        type: "ethernet"
        state: "present"
        addrs:
          - "dhcp"
        desc: "WAN"
        firewall:
          ipv4-unicast:
            - name: "WAN_Local"
              direction: "local"
            # - name: "WAN_In" # TODO
            #   direction: "in"

      - name: "lo"
        type: "loopback"
        state: "present"
        addrs: 
          - "172.22.132.163/32"
        desc: "fr-lil1"
        firewall:

    wireguard_interfaces:

      # iBGP fr-lil1<>us-ca1
      - name: "wg13"
        type: "wireguard"
        state: "present"
        addrs: 
          - "172.22.132.164/31"
        desc: "DN42_iBGP_fr-lil1<>us-ca1"
        privkey: "USCA1_PRIVKEY" # dotenv name
        port: "51802"
        firewall:
        wg_peers:
          - name: "fr-lil1"
            allowedips: 
              - "0.0.0.0/0"
              - "::/0"
            address: "185.154.155.193"
            port: "51801"
            pubkey: "qwjXj/6R9ThUnqeOAYN+MxM6CbIgzjS8WFDdXuyEpHY="
            keepalive: "60"

    bgp:
      asn: "4242421869"
      router_id: "172.22.132.162"

      prefixes:
        - prefix: "172.22.132.160"
          address_family: "ipv4-unicast"
          mask: "/27"
          state: "present"
        
        - prefix: "fd5f:2bd0:1feb::"
          address_family: "ipv6-unicast"
          mask: "/48"
          state: "present"


    prefix_lists:
      state: "replaced"   # replaced = delete x, then config
      config:
        - name: "BlockIPConflicts"
          desc: "Prevent Conflicting Routes"
          state: "present"
          rules:
          - rule_no: "10"
            state: "present"
            action: "permit"
            desc: "Internal IP Space"
            match:
              prefix: "10.0.0.0/8"
              le: 32

        - name: "DN42-Network"
          desc: "DN42 IPv4 Space"
          state: "present"
          rules:
          - rule_no: "10"
            state: "present"
            action: "permit"
            desc: "DN42 IP Space"
            match:
              prefix: "172.20.0.0/14"
              le: 32
              ge: 19

    prefix_lists6:
      state: "replaced"   # replaced = delete x, then config
      config:
        - name: "DN42-Network-v6"
          desc: "DN42 IPv6 Space"
          state: "present"
          rules:
          - rule_no: "10"
            state: "present"
            action: "permit"
            desc: "Internal IPv6 Space"
            match:
              prefix: "fd00::/8"
              le: 128

    ospf:
      state: ""
      config:
        ospf_redistribute:
          # - redistribute: "bgp"
          #   route_map: ""
          #   state: "absent"

        ospf_parameters:
          use_routerid: True
          routerid: "172.22.132.163"

        ospf_networks:
          - subnet: 172.22.132.160
            mask: /27
            area: 0
            state: present
